# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/zxe/Documents/FFmpeg-n4.4.1/doc/examples/ffmpeg-simple-player/simplest_ffmpeg_player

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/zxe/Documents/FFmpeg-n4.4.1/doc/examples/ffmpeg-simple-player/simplest_ffmpeg_player

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zxe/Documents/FFmpeg-n4.4.1/doc/examples/ffmpeg-simple-player/simplest_ffmpeg_player/CMakeFiles /home/zxe/Documents/FFmpeg-n4.4.1/doc/examples/ffmpeg-simple-player/simplest_ffmpeg_player//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/zxe/Documents/FFmpeg-n4.4.1/doc/examples/ffmpeg-simple-player/simplest_ffmpeg_player/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named player

# Build rule for target.
player: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 player
.PHONY : player

# fast build rule for target.
player/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/player.dir/build.make CMakeFiles/player.dir/build
.PHONY : player/fast

PackQueue.o: PackQueue.cpp.o
.PHONY : PackQueue.o

# target to build an object file
PackQueue.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/player.dir/build.make CMakeFiles/player.dir/PackQueue.cpp.o
.PHONY : PackQueue.cpp.o

PackQueue.i: PackQueue.cpp.i
.PHONY : PackQueue.i

# target to preprocess a source file
PackQueue.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/player.dir/build.make CMakeFiles/player.dir/PackQueue.cpp.i
.PHONY : PackQueue.cpp.i

PackQueue.s: PackQueue.cpp.s
.PHONY : PackQueue.s

# target to generate assembly for a file
PackQueue.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/player.dir/build.make CMakeFiles/player.dir/PackQueue.cpp.s
.PHONY : PackQueue.cpp.s

simplest_ffmpeg_player_su.o: simplest_ffmpeg_player_su.cpp.o
.PHONY : simplest_ffmpeg_player_su.o

# target to build an object file
simplest_ffmpeg_player_su.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/player.dir/build.make CMakeFiles/player.dir/simplest_ffmpeg_player_su.cpp.o
.PHONY : simplest_ffmpeg_player_su.cpp.o

simplest_ffmpeg_player_su.i: simplest_ffmpeg_player_su.cpp.i
.PHONY : simplest_ffmpeg_player_su.i

# target to preprocess a source file
simplest_ffmpeg_player_su.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/player.dir/build.make CMakeFiles/player.dir/simplest_ffmpeg_player_su.cpp.i
.PHONY : simplest_ffmpeg_player_su.cpp.i

simplest_ffmpeg_player_su.s: simplest_ffmpeg_player_su.cpp.s
.PHONY : simplest_ffmpeg_player_su.s

# target to generate assembly for a file
simplest_ffmpeg_player_su.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/player.dir/build.make CMakeFiles/player.dir/simplest_ffmpeg_player_su.cpp.s
.PHONY : simplest_ffmpeg_player_su.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... player"
	@echo "... PackQueue.o"
	@echo "... PackQueue.i"
	@echo "... PackQueue.s"
	@echo "... simplest_ffmpeg_player_su.o"
	@echo "... simplest_ffmpeg_player_su.i"
	@echo "... simplest_ffmpeg_player_su.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

